### ISSUE TITLE
Use https for included scripts

### ISSUE THREAD

**Issue by sal0max** [thiemo/brenizercalc#1]
Hello,

when using the [HTTPS Everywhere](https://www.eff.org/pt-br/https-everywhere) browser extension, 

> **http**://thiemo.github.io/brenizercalc/

gets forwarded to

> **https**://thiemo.github.io/brenizercalc/

This results in the page not functioning properly any more as the included angular script and the bootstrap css are linked via their insecure `http` links.
If you'd use `https://netdna.bootstrapcdn.com...` and `https://code.angularjs.org...` instead, everything would be fine again.

Thanks in advance! Your web app is really awesome!

**Comment by thiemo** [comment]
Hello, thank you, should be fixed 👍
